SET NOCOUNT ON;
DECLARE @START_DATE AS DATETIME = '2025-01-01'
DECLARE @END_DATE AS DATETIME = '2028-12-31'
DECLARE @TAX_YEAR AS NUMERIC(4,0) = 2026

DECLARE @ID	                                        		UNIQUEIDENTIFIER
DECLARE @JURISDICTION	                            		NUMERIC(2,0)
DECLARE @SALE_PRICE	                                		NUMERIC(18,0)
DECLARE @SALE_DATE	                                		DATETIME2
DECLARE @CONTRACT_DATE										DATETIME2
DECLARE @SALE_TYPE	                                		VARCHAR(50)
DECLARE @SALE_VALID_MARKET	                        		CHAR(1)
DECLARE @SALE_VALID_SRS	                            		CHAR(1)
DECLARE @VERIFY_REASON	                            		VARCHAR(20)
DECLARE @STATE_CODE	                                		VARCHAR(2)
DECLARE @UPDATE_DATE										DATETIME2
DECLARE @UPDATED_BY											VARCHAR(30)

DECLARE @CON_AMOUNT	                                    	NUMERIC(18,0)

DECLARE @MLS_SOURCE_NUMBER			                    	VARCHAR(50)
DECLARE @MLS_SOURCE_VALUE                                	NUMERIC(18,0)

DECLARE @TS_SOURCE_NUMBER			                    	VARCHAR(50)
DECLARE @TS_SOURCE_VALUE                                	NUMERIC(18,0)

DECLARE @SALE_PARCEL_COUNT									INT
DECLARE @SALE_IMP_COUNT										INT

DECLARE @SP_JURISDICTION	                            	NUMERIC(2,0)
DECLARE @SP_RECORD_TYPE	                                	VARCHAR(1)
DECLARE @SP_PARCEL_ID	                                	VARCHAR(36)
DECLARE @SP_TAX_YEAR	                                	NUMERIC(4,0)
DECLARE @SP_IS_PRIMARY	                                	BIT
DECLARE @SP_SALE_JURISDICTION	                        	NUMERIC(2,0)
DECLARE @SP_SALE_RECORD_TYPE	                        	VARCHAR(1)
DECLARE @SP_SALE_PARCEL_ID	                            	VARCHAR(36)
DECLARE @SP_SALE_TAX_YEAR	                            	NUMERIC(4,0)

DECLARE @PARCEL_ID											VARCHAR(36)
DECLARE @ADDITIONAL_PARCELS									VARCHAR(500)

DECLARE @SS_TAX_DIST	                                	VARCHAR(10)
DECLARE @SS_ACREAGE	                                    	NUMERIC(14,8)
DECLARE @SS_PROP_TYPE	                                	NUMERIC(4,0)
DECLARE @SS_SPECIFIC_PROP_TYPE	                        	NUMERIC(4,0)
DECLARE @SS_NBHD_CODE	                                	VARCHAR(20)
DECLARE @SS_LAND_DISTRICT	                            	NUMERIC(12,4)
DECLARE @SS_SUBDIVISION	                                	VARCHAR(200)
DECLARE @SS_TAX_STATUS										VARCHAR(1)
DECLARE @CY_ACREAGE	                                    	NUMERIC(14,8)
DECLARE @PY_ACREAGE	                                    	NUMERIC(14,8)
DECLARE @SS_FAA												NUMERIC(1,0)
DECLARE @CY_DETAIL_REVIEW_DATE								DATETIME2

DECLARE @PROP_TYPE_DESC										VARCHAR(250)
DECLARE @SPEC_PROP_TYPE_DESC								VARCHAR(250)
DECLARE @REGION												VARCHAR(250)
DECLARE @GROUP												VARCHAR(250)
DECLARE @NBHD_DESC											VARCHAR(250)
DECLARE @LAND_DISTRICT_DESC									VARCHAR(250)

DECLARE @TOTAL_LAND_VALUE									NUMERIC(15,0)
DECLARE @TOTAL_IMP_VALUE									NUMERIC(15,0)
DECLARE @TOTAL_VALUE										NUMERIC(15,0)
DECLARE @PRIMARY_VALUE_SOURCE								VARCHAR(25)

DECLARE @IMP_IMP_NO	                                    	NUMERIC(12,0)
DECLARE @IMP_JURISDICTION	                            	NUMERIC(2,0)
DECLARE @IMP_RECORD_TYPE                                	VARCHAR(1)
DECLARE @IMP_PARCEL_ID	                                	VARCHAR(36)
DECLARE @IMP_TAX_YEAR	                                	NUMERIC(4,0)

DECLARE @PY_QUALITY											NUMERIC(3,2)
DECLARE @PY_CONDITION										NUMERIC(3,2)
DECLARE @PY_BASEMENT_FINISHED								NUMERIC(6,0)
DECLARE @PY_BASEMENT_SF										NUMERIC(6,0)
DECLARE @PY_TOTAL_BEDROOMS									NUMERIC(2,0)
DECLARE @PY_TOTAL_FULL_BATHROOMS							NUMERIC(6,0)
DECLARE @PY_TOTAL_THREE_QUARTER_BATHROOMS					NUMERIC(6,0)
DECLARE @PY_TOTAL_HALF_BATHROOMS							NUMERIC(6,0)
DECLARE @PY_TOTAL_FIREPLACES								NUMERIC(6,0)
DECLARE @PY_TOTAL_KITCHENS									NUMERIC(6,0)
DECLARE @PY_TOTAL_LAUNDRY									NUMERIC(6,0)
DECLARE @PY_TOTAL_IMP_COUNT									NUMERIC(6,0)
DECLARE @PY_GLA												NUMERIC(8,0)
DECLARE @PY_YEAR_BUILT										NUMERIC(4,0)
DECLARE @PY_EFF_AGE											NUMERIC(4,0)
DECLARE @SS_QUALITY											NUMERIC(3,2)
DECLARE @SS_CONDITION										NUMERIC(3,2)
DECLARE @SS_BASEMENT_FINISHED								NUMERIC(6,0)
DECLARE @SS_BASEMENT_SF										NUMERIC(6,0)
DECLARE @SS_TOTAL_BEDROOMS									NUMERIC(2,0)
DECLARE @SS_TOTAL_FULL_BATHROOMS							NUMERIC(6,0)
DECLARE @SS_TOTAL_THREE_QUARTER_BATHROOMS					NUMERIC(6,0)
DECLARE @SS_TOTAL_HALF_BATHROOMS							NUMERIC(6,0)
DECLARE @SS_TOTAL_FIREPLACES								NUMERIC(6,0)
DECLARE @SS_TOTAL_KITCHENS									NUMERIC(6,0)
DECLARE @SS_TOTAL_LAUNDRY									NUMERIC(6,0)
DECLARE @SS_TOTAL_IMP_COUNT									NUMERIC(6,0)
DECLARE @SS_GLA												NUMERIC(8,0)
DECLARE @SS_YEAR_BUILT										NUMERIC(4,0)
DECLARE @SS_EFF_AGE											NUMERIC(4,0)
DECLARE @CY_QUALITY											NUMERIC(3,2)
DECLARE @CY_CONDITION										NUMERIC(3,2)
DECLARE @CY_BASEMENT_FINISHED								NUMERIC(6,0)
DECLARE @CY_BASEMENT_SF										NUMERIC(6,0)
DECLARE @CY_TOTAL_BEDROOMS									NUMERIC(2,0)
DECLARE @CY_TOTAL_FULL_BATHROOMS							NUMERIC(6,0)
DECLARE @CY_TOTAL_THREE_QUARTER_BATHROOMS					NUMERIC(6,0)
DECLARE @CY_TOTAL_HALF_BATHROOMS							NUMERIC(6,0)
DECLARE @CY_TOTAL_FIREPLACES								NUMERIC(6,0)
DECLARE @CY_TOTAL_KITCHENS									NUMERIC(6,0)
DECLARE @CY_TOTAL_LAUNDRY									NUMERIC(6,0)
DECLARE @CY_TOTAL_IMP_COUNT									NUMERIC(6,0)
DECLARE @CY_GLA												NUMERIC(8,0)
DECLARE @CY_YEAR_BUILT										NUMERIC(4,0)
DECLARE @CY_EFF_AGE											NUMERIC(4,0)


DECLARE @OUTPUT AS TABLE
	(
		JURISDICTION										NUMERIC(2,0),
		SALE_YEAR											NUMERIC(4,0),
		TAXABLE_STATUS										VARCHAR(1),
		MLS_SOURCE_NUMBER									VARCHAR(50),		
		MLS_SOURCE_VALUE									NUMERIC(18,0),
		TS_SOURCE_NUMBER									VARCHAR(50),
		TS_SOURCE_VALUE										NUMERIC(18,0),
		SALE_TYPE											VARCHAR(50),
		PARCEL_COUNT										NUMERIC(5,0),
		PARCEL_NUMBER										VARCHAR(36),
		ADDITIONAL_PARCEL_NUMBERS							VARCHAR(500),
		SALE_DATE											DATETIME2,
		UNDER_CONTRACT_DATE									DATETIME2,
		SALE_PRICE											NUMERIC(18,0),
		CONCESSIONS											NUMERIC(18,0),
		ADUSTED_SALES_PRICE									NUMERIC(18,0),
		PROP_TYPE					                      	NUMERIC(4,0),
		PROP_TYPE_DESCRIPTION								VARCHAR(250),
		SPECIFIC_PROP_TYPE			                      	NUMERIC(4,0),
		SPECIFIC_PROP_TYPE_DESCRIPTION						VARCHAR(250),
		TAX_DIST					                        VARCHAR(10),
		NBHD_REGION											VARCHAR(250),
		NBHD_GROUP											VARCHAR(250),
		NBHD_CODE					                      	VARCHAR(20),
		NBHD_DESCRIPTION									VARCHAR(250),
		SUBDIVISION					                      	VARCHAR(200),
		LAND_DISTRICT				                      	NUMERIC(12,4),
		LAND_DISTRICT_DESCRIPTION							VARCHAR(250),
		PY_ACREAGE	                                    	NUMERIC(14,8),
		PY_QUALITY											NUMERIC(3,2),
		PY_CONDITION										NUMERIC(3,2),
		PY_BASEMENT_FINISHED								NUMERIC(6,0),
		PY_BASEMENT_SF										NUMERIC(6,0),
		PY_TOTAL_BEDROOMS									NUMERIC(2,0),
		PY_TOTAL_FULL_BATHROOMS								NUMERIC(6,0),
		PY_TOTAL_THREE_QUARTER_BATHROOMS					NUMERIC(6,0),
		PY_TOTAL_HALF_BATHROOMS								NUMERIC(6,0),
		PY_TOTAL_FIREPLACES									NUMERIC(6,0),
		PY_TOTAL_KITCHENS									NUMERIC(6,0),
		PY_TOTAL_LAUNDRY									NUMERIC(6,0),
		PY_TOTAL_IMP_COUNT									NUMERIC(6,0),
		PY_GLA												NUMERIC(8,0),
		PY_YEAR_BUILT										NUMERIC(4,0),
		PY_EFF_AGE											NUMERIC(4,0),
		SS_ACREAGE	                                    	NUMERIC(14,8),
		SS_QUALITY											NUMERIC(3,2),
		SS_CONDITION										NUMERIC(3,2),
		SS_BASEMENT_FINISHED								NUMERIC(6,0),
		SS_BASEMENT_SF										NUMERIC(6,0),
		SS_TOTAL_BEDROOMS									NUMERIC(2,0),
		SS_TOTAL_FULL_BATHROOMS								NUMERIC(6,0),
		SS_TOTAL_THREE_QUARTER_BATHROOMS					NUMERIC(6,0),
		SS_TOTAL_HALF_BATHROOMS								NUMERIC(6,0),
		SS_TOTAL_FIREPLACES									NUMERIC(6,0),
		SS_TOTAL_KITCHENS									NUMERIC(6,0),
		SS_TOTAL_LAUNDRY									NUMERIC(6,0),
		SS_TOTAL_IMP_COUNT									NUMERIC(6,0),
		SS_GLA												NUMERIC(8,0),
		SS_YEAR_BUILT										NUMERIC(4,0),
		SS_EFF_AGE											NUMERIC(4,0),
		CY_ACREAGE	                                    	NUMERIC(14,8),
		CY_QUALITY											NUMERIC(3,2),
		CY_CONDITION										NUMERIC(3,2),
		CY_BASEMENT_FINISHED								NUMERIC(6,0),
		CY_BASEMENT_SF										NUMERIC(6,0),
		CY_TOTAL_BEDROOMS									NUMERIC(2,0),
		CY_TOTAL_FULL_BATHROOMS								NUMERIC(6,0),
		CY_TOTAL_THREE_QUARTER_BATHROOMS					NUMERIC(6,0),
		CY_TOTAL_HALF_BATHROOMS								NUMERIC(6,0),
		CY_TOTAL_FIREPLACES									NUMERIC(6,0),
		CY_TOTAL_KITCHENS									NUMERIC(6,0),
		CY_TOTAL_LAUNDRY									NUMERIC(6,0),
		CY_TOTAL_IMP_COUNT									NUMERIC(6,0),
		CY_GLA												NUMERIC(8,0),
		CY_YEAR_BUILT										NUMERIC(4,0),
		CY_EFF_AGE											NUMERIC(4,0),
		TAX_YEAR											NUMERIC(4,0),
		LAND_VALUE											NUMERIC(15,0),
		IMP_VALUE											NUMERIC(15,0),
		TOTAL_VALUE											NUMERIC(15,0),
		SALE_VALID_MARKET									VARCHAR(1),
		SALE_VALID_SRS										VARCHAR(1),
		STATE_CODE											VARCHAR(1),
		VERIFY_REASON										VARCHAR(20),
		FAA_FLAG											NUMERIC(1),
		DETAIL_REVIEW_DATE									DATETIME2,
		DETAIL_REVIEW_AREA									VARCHAR(3),
		RATIO												NUMERIC(10,2)
	)
DECLARE @IMP_RES_TYPE AS TABLE
	(
		IMP_NO	                                    		NUMERIC(12,0),
		JURISDICTION	                            		NUMERIC(2,0),
		RECORD_TYPE	                                		VARCHAR(1),
		PARCEL_ID	                                		VARCHAR(36),
		TAX_YEAR	                                		NUMERIC(4,0),
		QUALITY	                                    		NUMERIC(3,2),
		CONDITION	                                		NUMERIC(3,2),
		YEAR_BUILT	                                		NUMERIC(4,0),
		EFF_YEAR_BUILT	                            		NUMERIC(4,0),
		GLA	                                        		NUMERIC(8,0),
		BSMT	                                    		NUMERIC(6,0),
		BSMT_FINISH_PCT	                            		NUMERIC(3,2),
		GLA_BEDROOMS	                            		NUMERIC(2,0),
		ROW_ID												INT IDENTITY(1,1) NOT NULL,
		INDEX IDX_ROWID										NONCLUSTERED (ROW_ID)
	)

DECLARE @SALES_TYPE AS TABLE
	(
		ID													UNIQUEIDENTIFIER NULL,
		JURISDICTION										NUMERIC(2, 0) NULL,
		SALE_PRICE											NUMERIC(18, 0) NULL,
		SALE_DATE											DATETIME2 NULL,
		CONTRACT_DATE										DATETIME2 NULL,
		SALE_TYPE											VARCHAR(50) NULL,
		SALE_VALID_MARKET									CHAR(1) NULL,
		SALE_VALID_SRS										CHAR(1) NULL,
		VERIFY_REASON										VARCHAR(20) NULL,
		STATE_CODE											VARCHAR(2) NULL,
		UPDATE_DATE											DATETIME2 NULL,
		UPDATED_BY											VARCHAR(30) NULL,
		ROW_ID												INT IDENTITY(1,1) NOT NULL,
		INDEX IDX_ROWID										NONCLUSTERED (ROW_ID)
	)

DECLARE @SALE_PARCEL_TYPE AS TABLE
	(
		SP_JURISDICTION	                            		NUMERIC(2,0),
		SP_RECORD_TYPE										VARCHAR(1),
		SP_PARCEL_ID										VARCHAR(36),
		SP_TAX_YEAR	                                		NUMERIC(4,0),
		SP_IS_PRIMARY										BIT,
		SP_SALE_JURISDICTION								NUMERIC(2,0),
		SP_SALE_RECORD_TYPE	                        		VARCHAR(1),
		SP_SALE_PARCEL_ID									VARCHAR(36),
		SP_SALE_TAX_YEAR									NUMERIC(4,0),
		ROW_ID												INT	IDENTITY(1,1) NOT NULL,
		INDEX IDX_ROWID										NONCLUSTERED (ROW_ID)
	)


INSERT INTO @SALES_TYPE
SELECT
	ID,
	JURISDICTION,
	SALE_PRICE,
	SALE_DATE,
	CONTRACT_DATE,
	SALE_TYPE,
	SALE_VALID_MARKET,
	SALE_VALID_SRS,
	VERIFY_REASON,
	STATE_CODE,
	UPDATE_DATE,
	UPDATED_BY
FROM CAMA.SALE
WHERE JURISDICTION != 0
	AND SALE_DATE BETWEEN @START_DATE AND @END_DATE

DECLARE @MIN_ID INT = (SELECT MIN(ROW_ID) FROM @SALES_TYPE)
DECLARE @MAX_ID INT = (SELECT MAX(ROW_ID) FROM @SALES_TYPE)

WHILE @MIN_ID <= @MAX_ID
BEGIN
	SET @CON_AMOUNT								=	0
	SET @MLS_SOURCE_NUMBER						=	NULL
	SET @MLS_SOURCE_VALUE						=	NULL
	SET @TS_SOURCE_NUMBER						=	NULL
	SET @TS_SOURCE_VALUE						=	NULL
	SET @SALE_PARCEL_COUNT						=	0
	SET @PARCEL_ID								=	NULL
	SET @ADDITIONAL_PARCELS						=	''
	SET @SS_TAX_STATUS							=	NULL
	SET @SS_TAX_DIST							=	NULL
	SET @SS_ACREAGE								=	NULL
	SET @SS_PROP_TYPE							=	NULL
	SET @SS_SPECIFIC_PROP_TYPE					=	NULL
	SET @SS_NBHD_CODE							=	NULL
	SET @SS_LAND_DISTRICT						=	NULL
	SET @SS_SUBDIVISION							=	NULL
	SET @CY_ACREAGE								=	NULL
	SET @PY_ACREAGE								=	NULL
	SET @PROP_TYPE_DESC							=	NULL
	SET @SPEC_PROP_TYPE_DESC					=	NULL
	SET @REGION									=	NULL
	SET @GROUP									=	NULL
	SET @NBHD_DESC								=	NULL
	SET @LAND_DISTRICT_DESC						=	NULL
	SET @SS_FAA									=	NULL
	SET @CY_DETAIL_REVIEW_DATE					=	NULL
	SET @PRIMARY_VALUE_SOURCE					=	NULL
	SET @TOTAL_VALUE							=	0
	SET @TOTAL_IMP_VALUE						=	0
	SET @TOTAL_LAND_VALUE						=	0
	SET @PY_BASEMENT_SF							=	NULL
	SET @PY_TOTAL_BEDROOMS						=	NULL
	SET @PY_TOTAL_FULL_BATHROOMS				=	NULL
	SET @PY_TOTAL_THREE_QUARTER_BATHROOMS		=	NULL
	SET @PY_TOTAL_HALF_BATHROOMS				=	NULL
	SET @PY_TOTAL_FIREPLACES					=	NULL
	SET @PY_TOTAL_KITCHENS						=	NULL
	SET @PY_TOTAL_LAUNDRY						=	NULL
	SET @PY_TOTAL_IMP_COUNT						=	NULL
	SET @PY_GLA									=	NULL
	SET @PY_YEAR_BUILT							=	NULL
	SET @PY_EFF_AGE								=	NULL
	SET @SS_QUALITY								=	NULL
	SET @SS_CONDITION							=	NULL
	SET @SS_BASEMENT_FINISHED					=	NULL
	SET @SS_BASEMENT_SF							=	NULL
	SET @SS_TOTAL_BEDROOMS						=	NULL
	SET @SS_TOTAL_FULL_BATHROOMS				=	NULL
	SET @SS_TOTAL_THREE_QUARTER_BATHROOMS		=	NULL
	SET @SS_TOTAL_HALF_BATHROOMS				=	NULL
	SET @SS_TOTAL_FIREPLACES					=	NULL
	SET @SS_TOTAL_KITCHENS						=	NULL
	SET @SS_TOTAL_LAUNDRY						=	NULL
	SET @SS_TOTAL_IMP_COUNT						=	NULL
	SET @SS_GLA									=	NULL
	SET @SS_YEAR_BUILT							=	NULL
	SET @SS_EFF_AGE								=	NULL
	SET @CY_QUALITY								=	NULL
	SET @CY_CONDITION							=	NULL
	SET @CY_BASEMENT_FINISHED					=	NULL
	SET @CY_BASEMENT_SF							=	NULL
	SET @CY_TOTAL_BEDROOMS						=	NULL
	SET @CY_TOTAL_FULL_BATHROOMS				=	NULL
	SET @CY_TOTAL_THREE_QUARTER_BATHROOMS		=	NULL
	SET @CY_TOTAL_HALF_BATHROOMS				=	NULL
	SET @CY_TOTAL_FIREPLACES					=	NULL
	SET @CY_TOTAL_KITCHENS						=	NULL
	SET @CY_TOTAL_LAUNDRY						=	NULL
	SET @CY_TOTAL_IMP_COUNT						=	NULL
	SET @CY_GLA									=	NULL
	SET @CY_YEAR_BUILT							=	NULL
	SET @CY_EFF_AGE								=	NULL



	DELETE FROM @SALE_PARCEL_TYPE
	SELECT
		@ID	                                        	=	G.ID,
		@JURISDICTION	                            	=	G.JURISDICTION,
		@SALE_PRICE	                                	=	G.SALE_PRICE,
		@SALE_DATE	                                	=	G.SALE_DATE,
		@CONTRACT_DATE									=	G.CONTRACT_DATE,
		@SALE_TYPE	                                	=	G.SALE_TYPE,
		@SALE_VALID_MARKET	                        	=	G.SALE_VALID_MARKET,
		@SALE_VALID_SRS	                            	=	G.SALE_VALID_SRS,
		@VERIFY_REASON	                            	=	G.VERIFY_REASON,
		@STATE_CODE	                                	=	G.STATE_CODE,
		@UPDATE_DATE									=	G.UPDATE_DATE,
		@UPDATED_BY										=	G.UPDATED_BY
	FROM @SALES_TYPE G
	WHERE G.ROW_ID = @MIN_ID

	SELECT
		@CON_AMOUNT = SUM(AMOUNT)
	FROM CAMA.SALE_SALE_CONCESSION
	WHERE SALE_ID = @ID
		AND JURISDICTION = @JURISDICTION
		AND IS_CALCULATED = 1

	SELECT
		@MLS_SOURCE_NUMBER = SSS.SOURCE_RECORD_NUMBER,
		@MLS_SOURCE_VALUE = SSS.SALE_PRICE
	FROM CAMA.SALE_SALE_SOURCE SSS
	INNER JOIN CAMA.SALE_SOURCE SS
		ON SSS.JURISDICTION = SS.JURISDICTION
		AND SSS.SALE_SOURCE_ID = SS.ID
	WHERE SSS.SALE_ID = @ID
		AND SSS.JURISDICTION = @JURISDICTION
		AND SS.SALE_SOURCE_NAME = 'MLS'

	SELECT
		@TS_SOURCE_NUMBER = SSS.SOURCE_RECORD_NUMBER,
		@TS_SOURCE_VALUE = SSS.SALE_PRICE
	FROM CAMA.SALE_SALE_SOURCE SSS
	INNER JOIN CAMA.SALE_SOURCE SS
		ON SSS.JURISDICTION = SS.JURISDICTION
		AND SSS.SALE_SOURCE_ID = SS.ID
	WHERE SSS.SALE_ID = @ID
		AND SSS.JURISDICTION = @JURISDICTION
		AND SS.SALE_SOURCE_NAME = 'TRANSFER SURVEY'

	INSERT INTO @SALE_PARCEL_TYPE
	SELECT
		JURISDICTION,
		RECORD_TYPE,
		PARCEL_ID,
		TAX_YEAR,
		IS_PRIMARY,
		SALE_JURISDICTION,
		SALE_RECORD_TYPE,
		SALE_PARCEL_ID,
		SALE_TAX_YEAR
	FROM CAMA.SALE_PARCEL
	WHERE SALE_ID = @ID
		AND TAX_YEAR = @TAX_YEAR
	ORDER BY IS_PRIMARY DESC

	DECLARE @SP_MIN_ID INT = NULL
	SET @SP_MIN_ID = (SELECT MIN(ROW_ID) FROM @SALE_PARCEL_TYPE)
	DECLARE @SP_MAX_ID INT = NULL
	SET @SP_MAX_ID = (SELECT MAX(ROW_ID) FROM @SALE_PARCEL_TYPE)	

	IF @SP_MAX_ID IS NOT NULL
	BEGIN
		WHILE @SP_MIN_ID <= @SP_MAX_ID
		BEGIN
			SET @SALE_PARCEL_COUNT += 1

			SELECT
				@SP_JURISDICTION	                            	=	G.SP_JURISDICTION,
				@SP_RECORD_TYPE	                                	=	G.SP_RECORD_TYPE,
				@SP_PARCEL_ID	                                	=	G.SP_PARCEL_ID,
				@SP_TAX_YEAR	                                	=	G.SP_TAX_YEAR,
				@SP_IS_PRIMARY	                                	=	G.SP_IS_PRIMARY,
				@SP_SALE_JURISDICTION	                        	=	G.SP_SALE_JURISDICTION,
				@SP_SALE_RECORD_TYPE	                        	=	G.SP_SALE_RECORD_TYPE,
				@SP_SALE_PARCEL_ID	                            	=	G.SP_SALE_PARCEL_ID,
				@SP_SALE_TAX_YEAR	                            	=	G.SP_SALE_TAX_YEAR
			FROM @SALE_PARCEL_TYPE G
			WHERE ROW_ID = @SP_MIN_ID

			

			IF @SALE_PARCEL_COUNT = 1
			BEGIN
				SET @PARCEL_ID = @SP_PARCEL_ID
				SELECT
					@SS_TAX_STATUS									=	TAXABLE_STATUS,
					@SS_TAX_DIST									=	TAX_DIST,
					@SS_ACREAGE										=	ACREAGE,
					@SS_PROP_TYPE									=	PROP_TYPE,
					@SS_SPECIFIC_PROP_TYPE							=	SPECIFIC_PROP_TYPE,
					@SS_NBHD_CODE									=	NBHD_CODE,
					@SS_LAND_DISTRICT								=	LAND_DISTRICT,
					@SS_SUBDIVISION									=	SUBDIVISION,
					@SS_FAA											=	FAA
				FROM CAMA.PARCEL 
				WHERE JURISDICTION = @SP_SALE_JURISDICTION
					AND RECORD_TYPE = @SP_SALE_RECORD_TYPE
					AND PARCEL_ID = @SP_SALE_PARCEL_ID
					AND TAX_YEAR = @SP_SALE_TAX_YEAR

				SELECT
					@PY_ACREAGE										=	ACREAGE			
				FROM CAMA.PARCEL 
				WHERE JURISDICTION = @SP_JURISDICTION
					AND RECORD_TYPE = @SP_RECORD_TYPE
					AND PARCEL_ID = @SP_PARCEL_ID
					AND TAX_YEAR = @SP_TAX_YEAR - 1

				SELECT
					@CY_ACREAGE										=	ACREAGE,
					@CY_DETAIL_REVIEW_DATE							=	REVIEWED_DATE
				FROM CAMA.PARCEL 
				WHERE JURISDICTION = @SP_JURISDICTION
					AND RECORD_TYPE = @SP_RECORD_TYPE
					AND PARCEL_ID = @SP_PARCEL_ID
					AND TAX_YEAR = @SP_TAX_YEAR

				SELECT
					@PRIMARY_VALUE_SOURCE							=	VALUE_SOURCE
				FROM CAMA.PARCEL_VALUES
				WHERE JURISDICTION = @SP_JURISDICTION
					AND RECORD_TYPE = @SP_RECORD_TYPE
					AND PARCEL_ID = @SP_PARCEL_ID
					AND TAX_YEAR = @SP_TAX_YEAR
					AND IS_PRIMARY = 1

				SELECT
					@TOTAL_VALUE									+=	SUM(TOTAL_VALUE),
					@TOTAL_IMP_VALUE								+=	SUM(IIF(ASMT_TYPE = 'IMP',TOTAL_VALUE,0)),
					@TOTAL_LAND_VALUE								+=	SUM(IIF(ASMT_TYPE = 'LAND',TOTAL_VALUE,0))
				FROM CAMA.PARCEL_VALUE_DETAIL
				WHERE JURISDICTION = @SP_JURISDICTION
					AND RECORD_TYPE = @SP_RECORD_TYPE
					AND PARCEL_ID = @SP_PARCEL_ID
					AND TAX_YEAR = @SP_TAX_YEAR
					AND VALUE_SOURCE = @PRIMARY_VALUE_SOURCE
					AND IS_GREENBELT = 0
			END
			ELSE
			BEGIN
				SET @ADDITIONAL_PARCELS += @SP_PARCEL_ID + ', '
				SELECT
					@SS_TAX_STATUS									=	IIF(TAXABLE_STATUS!=@SS_TAX_STATUS,NULL,@SS_TAX_STATUS),
					@SS_TAX_DIST									=	IIF(TAX_DIST!=@SS_TAX_DIST,NULL,@SS_TAX_DIST),
					@SS_ACREAGE										+=	ACREAGE,
					@SS_PROP_TYPE									=	IIF(PROP_TYPE!=@SS_PROP_TYPE,NULL,@SS_PROP_TYPE),
					@SS_SPECIFIC_PROP_TYPE							=	IIF(SPECIFIC_PROP_TYPE!=@SS_SPECIFIC_PROP_TYPE,NULL,@SS_SPECIFIC_PROP_TYPE),
					@SS_NBHD_CODE									=	IIF(NBHD_CODE!=@SS_NBHD_CODE,NULL,@SS_NBHD_CODE),
					@SS_LAND_DISTRICT								=	IIF(LAND_DISTRICT!=@SS_LAND_DISTRICT,NULL,@SS_LAND_DISTRICT),
					@SS_SUBDIVISION									=	IIF(SUBDIVISION!=@SS_SUBDIVISION,NULL,@SS_SUBDIVISION),
					@SS_FAA											=	IIF(FAA!=@SS_FAA,NULL,@SS_FAA)
				FROM CAMA.PARCEL 
				WHERE JURISDICTION = @SP_SALE_JURISDICTION
					AND RECORD_TYPE = @SP_SALE_RECORD_TYPE
					AND PARCEL_ID = @SP_SALE_PARCEL_ID
					AND TAX_YEAR = @SP_SALE_TAX_YEAR

				SELECT
					@PY_ACREAGE										+=	ACREAGE			
				FROM CAMA.PARCEL 
				WHERE JURISDICTION = @SP_JURISDICTION
					AND RECORD_TYPE = @SP_RECORD_TYPE
					AND PARCEL_ID = @SP_PARCEL_ID
					AND TAX_YEAR = @SP_TAX_YEAR - 1

				SELECT
					@CY_ACREAGE										+=	ACREAGE,
					@CY_DETAIL_REVIEW_DATE							= IIF(@CY_DETAIL_REVIEW_DATE>REVIEWED_DATE,REVIEWED_DATE,@CY_DETAIL_REVIEW_DATE)
				FROM CAMA.PARCEL 
				WHERE JURISDICTION = @SP_JURISDICTION
					AND RECORD_TYPE = @SP_RECORD_TYPE
					AND PARCEL_ID = @SP_PARCEL_ID
					AND TAX_YEAR = @SP_TAX_YEAR

				SELECT
					@PRIMARY_VALUE_SOURCE							=	VALUE_SOURCE
				FROM CAMA.PARCEL_VALUES
				WHERE JURISDICTION = @SP_JURISDICTION
					AND RECORD_TYPE = @SP_RECORD_TYPE
					AND PARCEL_ID = @SP_PARCEL_ID
					AND TAX_YEAR = @SP_TAX_YEAR
					AND IS_PRIMARY = 1

				SELECT
					@TOTAL_VALUE									+=	SUM(TOTAL_VALUE),
					@TOTAL_IMP_VALUE								+=	SUM(IIF(ASMT_TYPE = 'IMP',TOTAL_VALUE,0)),
					@TOTAL_LAND_VALUE								+=	SUM(IIF(ASMT_TYPE = 'LAND',TOTAL_VALUE,0))
				FROM CAMA.PARCEL_VALUE_DETAIL
				WHERE JURISDICTION = @SP_JURISDICTION
					AND RECORD_TYPE = @SP_RECORD_TYPE
					AND PARCEL_ID = @SP_PARCEL_ID
					AND TAX_YEAR = @SP_TAX_YEAR
					AND VALUE_SOURCE = @PRIMARY_VALUE_SOURCE
					AND IS_GREENBELT = 0
			END
			SET @SP_MIN_ID += 1
		END

		IF @ADDITIONAL_PARCELS != ''
		BEGIN
			SET @ADDITIONAL_PARCELS = LEFT(@ADDITIONAL_PARCELS,LEN(@ADDITIONAL_PARCELS) - 1)
		END

		IF @SS_PROP_TYPE IS NOT NULL
		BEGIN
			SELECT
				@PROP_TYPE_DESC = DESCRIPTION
			FROM CAMA.PROP_TYPE_CODES
			WHERE JURISDICTION = @JURISDICTION
				AND PROP_TYPE = @SS_PROP_TYPE
				AND CODE_TYPE = 'PT'
		END

		IF @SS_SPECIFIC_PROP_TYPE IS NOT NULL
		BEGIN
			SELECT
				@SPEC_PROP_TYPE_DESC = DESCRIPTION
			FROM CAMA.PROP_TYPE_CODES
			WHERE JURISDICTION = @JURISDICTION
				AND PROP_TYPE = @SS_SPECIFIC_PROP_TYPE
				AND CODE_TYPE = 'SPT'
		END

		IF @SS_NBHD_CODE IS NOT NULL
		BEGIN
			SELECT
				@REGION = NBHD_REGION,
				@GROUP = NBHD_GROUP,
				@NBHD_DESC = DESCRIPTION
			FROM CAMA.NEIGHBORHOOD
			WHERE JURISDICTION = @JURISDICTION
				AND NBHD_CODE = @SS_NBHD_CODE
		END

		IF @SS_LAND_DISTRICT IS NOT NULL
		BEGIN
			SELECT
				@LAND_DISTRICT_DESC = DESCRIPTION
			FROM CAMA.LAND_DISTRICT
			WHERE JURISDICTION = @JURISDICTION
				AND LAND_DISTRICT = @SS_LAND_DISTRICT
				AND TAX_YEAR = @SP_SALE_TAX_YEAR
		END
		DELETE @IMP_RES_TYPE
		INSERT INTO @IMP_RES_TYPE
		SELECT
			IMP_NO	                                    	=	IR.IMP_NO,
			JURISDICTION	                            	=	IR.JURISDICTION,
			RECORD_TYPE			                            =	IR.RECORD_TYPE,
			PARCEL_ID	                                	=	IR.PARCEL_ID,
			TAX_YEAR	                                	=	IR.TAX_YEAR,
			QUALITY	                                    	=	IR.QUALITY,
			CONDITION	                                	=	IR.CONDITION,
			YEAR_BUILT	                                	=	IR.YEAR_BUILT,
			EFF_AGE	                            			=	IR.TAX_YEAR - IR.EFF_YEAR_BUILT,
			GLA	                                        	=	IR.GLA,
			BSMT	                                    	=	IR.BSMT,
			BSMT_FINISH_PCT	                            	=	IR.BSMT_FINISH_PCT,
			GLA_BEDROOMS	                            	=	IR.GLA_BEDROOMS
		FROM CAMA.IMP_RES IR
		INNER JOIN @SALE_PARCEL_TYPE SPT
			ON IR.JURISDICTION = SPT.SP_JURISDICTION
			AND IR.RECORD_TYPE = SPT.SP_RECORD_TYPE
			AND IR.PARCEL_ID = SPT.SP_PARCEL_ID
			AND IR.TAX_YEAR = SPT.SP_TAX_YEAR - 1

		DECLARE @I_MIN_ID INT = NULL
		SET @I_MIN_ID = (SELECT MIN(ROW_ID) FROM @IMP_RES_TYPE)
		DECLARE @I_MAX_ID INT = NULL
		SET @I_MAX_ID = (SELECT MAX(ROW_ID) FROM @IMP_RES_TYPE)	

		SET @PY_TOTAL_IMP_COUNT = 0
		IF @I_MAX_ID IS NOT NULL
		BEGIN
			WHILE @I_MIN_ID <=@I_MAX_ID
			BEGIN
				SET @PY_TOTAL_IMP_COUNT += 1

				IF @PY_TOTAL_IMP_COUNT = 1
				BEGIN
					SELECT
						@IMP_IMP_NO	                                    	=	IR.IMP_NO,
						@IMP_JURISDICTION	                            	=	IR.JURISDICTION,
						@IMP_RECORD_TYPE	                                =	IR.RECORD_TYPE,
						@IMP_PARCEL_ID	                                	=	IR.PARCEL_ID,
						@IMP_TAX_YEAR	                                	=	IR.TAX_YEAR,
						@PY_QUALITY	                                    	=	IR.QUALITY,
						@PY_CONDITION	                                	=	IR.CONDITION,
						@PY_YEAR_BUILT	                                	=	IR.YEAR_BUILT,
						@PY_EFF_AGE	                            			=	IR.TAX_YEAR - IR.EFF_YEAR_BUILT,
						@PY_GLA	                                        	=	IR.GLA,
						@PY_BASEMENT_SF	                                    =	IR.BSMT,
						@PY_BASEMENT_FINISHED                            	=	IR.BSMT * IR.BSMT_FINISH_PCT,
						@PY_TOTAL_BEDROOMS	                            	=	IR.GLA_BEDROOMS
					FROM @IMP_RES_TYPE IR
					WHERE IR.ROW_ID = @I_MIN_ID

					SELECT
						@PY_TOTAL_FULL_BATHROOMS							=	P.FULL_BATHS_3 + P.FULL_BATHS_4 + P.DELUXE_BATHS_5 + P.LUXURY_BATHS_6,
						@PY_TOTAL_HALF_BATHROOMS							=	P.HALF_BATHS_2,
						@PY_TOTAL_THREE_QUARTER_BATHROOMS					=	P.THREE_QTR_BATHS_3,
						@PY_TOTAL_LAUNDRY									=	P.ROUGH_IN_FIXTURES
					FROM CAMA.IMP_RES_PLUMBING P
					WHERE P.IMP_NO = @IMP_IMP_NO
						AND P.JURISDICTION = @IMP_JURISDICTION
						AND P.RECORD_TYPE = @IMP_RECORD_TYPE
						AND P.PARCEL_ID = @IMP_PARCEL_ID
						AND P.TAX_YEAR = @IMP_TAX_YEAR

					SELECT
						@PY_TOTAL_FIREPLACES = SUM(IIF(A.COST_CODE != 1200,A.UNIT_COUNT,0)),
						@PY_TOTAL_KITCHENS = SUM(IIF(A.COST_CODE = 1200,A.UNIT_COUNT,0))
					FROM CAMA.IMP_RES_ADD_ONS A
					WHERE A.IMP_NO = @IMP_IMP_NO
						AND A.JURISDICTION = @IMP_JURISDICTION
						AND A.RECORD_TYPE = @IMP_RECORD_TYPE
						AND A.PARCEL_ID = @IMP_PARCEL_ID
						AND A.TAX_YEAR = @IMP_TAX_YEAR
						AND (A.COST_CODE = 1200 OR A.COST_CODE BETWEEN 1100 AND 1115)
				END
				ELSE
				BEGIN
					SELECT
						@IMP_IMP_NO	                                    	=	IR.IMP_NO,
						@IMP_JURISDICTION	                            	=	IR.JURISDICTION,
						@IMP_RECORD_TYPE	                                =	IR.RECORD_TYPE,
						@IMP_PARCEL_ID	                                	=	IR.PARCEL_ID,
						@IMP_TAX_YEAR	                                	=	IR.TAX_YEAR,
						@PY_QUALITY	                                    	=	IIF(@PY_QUALITY != IR.QUALITY,NULL,@PY_QUALITY),
						@PY_CONDITION	                                	=	IIF(@PY_CONDITION != IR.CONDITION,NULL,@PY_CONDITION),
						@PY_YEAR_BUILT	                                	=	IIF(@PY_YEAR_BUILT != IR.YEAR_BUILT,NULL,@PY_YEAR_BUILT),
						@PY_EFF_AGE	                            			=	IIF(@PY_EFF_AGE != IR.TAX_YEAR - IR.EFF_YEAR_BUILT,NULL,@PY_EFF_AGE),
						@PY_GLA	                                        	+=	IR.GLA,
						@PY_BASEMENT_SF	                                    +=	IR.BSMT,
						@PY_BASEMENT_FINISHED                            	+=	IR.BSMT * IR.BSMT_FINISH_PCT,
						@PY_TOTAL_BEDROOMS	                            	+=	IR.GLA_BEDROOMS
					FROM @IMP_RES_TYPE IR
					WHERE IR.ROW_ID = @I_MIN_ID

					SELECT
						@PY_TOTAL_FULL_BATHROOMS							+=	P.FULL_BATHS_3 + P.FULL_BATHS_4 + P.DELUXE_BATHS_5 + P.LUXURY_BATHS_6,
						@PY_TOTAL_HALF_BATHROOMS							+=	P.HALF_BATHS_2,
						@PY_TOTAL_THREE_QUARTER_BATHROOMS					+=	P.THREE_QTR_BATHS_3,
						@PY_TOTAL_LAUNDRY									+=	P.ROUGH_IN_FIXTURES
					FROM CAMA.IMP_RES_PLUMBING P
					WHERE P.IMP_NO = @IMP_IMP_NO
						AND P.JURISDICTION = @IMP_JURISDICTION
						AND P.RECORD_TYPE = @IMP_RECORD_TYPE
						AND P.PARCEL_ID = @IMP_PARCEL_ID
						AND P.TAX_YEAR = @IMP_TAX_YEAR

					SELECT
						@PY_TOTAL_FIREPLACES += SUM(IIF(A.COST_CODE != 1200,A.UNIT_COUNT,0)),
						@PY_TOTAL_KITCHENS += SUM(IIF(A.COST_CODE = 1200,A.UNIT_COUNT,0))
					FROM CAMA.IMP_RES_ADD_ONS A
					WHERE A.IMP_NO = @IMP_IMP_NO
						AND A.JURISDICTION = @IMP_JURISDICTION
						AND A.RECORD_TYPE = @IMP_RECORD_TYPE
						AND A.PARCEL_ID = @IMP_PARCEL_ID
						AND A.TAX_YEAR = @IMP_TAX_YEAR
						AND (A.COST_CODE = 1200 OR A.COST_CODE BETWEEN 1100 AND 1115)
				END				
				SET @I_MIN_ID += 1
			END
		END
		DELETE @IMP_RES_TYPE
		INSERT INTO @IMP_RES_TYPE
		SELECT
			IMP_NO	                                    	=	IR.IMP_NO,
			JURISDICTION	                            	=	IR.JURISDICTION,
			RECORD_TYPE			                            =	IR.RECORD_TYPE,
			PARCEL_ID	                                	=	IR.PARCEL_ID,
			TAX_YEAR	                                	=	IR.TAX_YEAR,
			QUALITY	                                    	=	IR.QUALITY,
			CONDITION	                                	=	IR.CONDITION,
			YEAR_BUILT	                                	=	IR.YEAR_BUILT,
			EFF_AGE	                            			=	IR.TAX_YEAR - IR.EFF_YEAR_BUILT,
			GLA	                                        	=	IR.GLA,
			BSMT	                                    	=	IR.BSMT,
			BSMT_FINISH_PCT	                            	=	IR.BSMT_FINISH_PCT,
			GLA_BEDROOMS	                            	=	IR.GLA_BEDROOMS
		FROM CAMA.IMP_RES IR
		INNER JOIN @SALE_PARCEL_TYPE SPT
			ON IR.JURISDICTION = SPT.SP_SALE_JURISDICTION
			AND IR.RECORD_TYPE = SPT.SP_SALE_RECORD_TYPE
			AND IR.PARCEL_ID = SPT.SP_SALE_PARCEL_ID
			AND IR.TAX_YEAR = SPT.SP_SALE_TAX_YEAR

		SET @I_MIN_ID = NULL
		SET @I_MIN_ID = (SELECT MIN(ROW_ID) FROM @IMP_RES_TYPE)
		SET @I_MAX_ID = NULL
		SET @I_MAX_ID = (SELECT MAX(ROW_ID) FROM @IMP_RES_TYPE)	

		SET @SS_TOTAL_IMP_COUNT = 0
		IF @I_MAX_ID IS NOT NULL
		BEGIN
			WHILE @I_MIN_ID <=@I_MAX_ID
			BEGIN
				SET @SS_TOTAL_IMP_COUNT += 1

				IF @SS_TOTAL_IMP_COUNT = 1
				BEGIN
					SELECT
						@IMP_IMP_NO	                                    	=	IR.IMP_NO,
						@IMP_JURISDICTION	                            	=	IR.JURISDICTION,
						@IMP_RECORD_TYPE	                                =	IR.RECORD_TYPE,
						@IMP_PARCEL_ID	                                	=	IR.PARCEL_ID,
						@IMP_TAX_YEAR	                                	=	IR.TAX_YEAR,
						@SS_QUALITY	                                    	=	IR.QUALITY,
						@SS_CONDITION	                                	=	IR.CONDITION,
						@SS_YEAR_BUILT	                                	=	IR.YEAR_BUILT,
						@SS_EFF_AGE	                            			=	IR.TAX_YEAR - IR.EFF_YEAR_BUILT,
						@SS_GLA	                                        	=	IR.GLA,
						@SS_BASEMENT_SF	                                    =	IR.BSMT,
						@SS_BASEMENT_FINISHED                            	=	IR.BSMT * IR.BSMT_FINISH_PCT,
						@SS_TOTAL_BEDROOMS	                            	=	IR.GLA_BEDROOMS
					FROM @IMP_RES_TYPE IR
					WHERE IR.ROW_ID = @I_MIN_ID

					SELECT
						@SS_TOTAL_FULL_BATHROOMS							=	P.FULL_BATHS_3 + P.FULL_BATHS_4 + P.DELUXE_BATHS_5 + P.LUXURY_BATHS_6,
						@SS_TOTAL_HALF_BATHROOMS							=	P.HALF_BATHS_2,
						@SS_TOTAL_THREE_QUARTER_BATHROOMS					=	P.THREE_QTR_BATHS_3,
						@SS_TOTAL_LAUNDRY									=	P.ROUGH_IN_FIXTURES
					FROM CAMA.IMP_RES_PLUMBING P
					WHERE P.IMP_NO = @IMP_IMP_NO
						AND P.JURISDICTION = @IMP_JURISDICTION
						AND P.RECORD_TYPE = @IMP_RECORD_TYPE
						AND P.PARCEL_ID = @IMP_PARCEL_ID
						AND P.TAX_YEAR = @IMP_TAX_YEAR

					SELECT
						@SS_TOTAL_FIREPLACES = SUM(IIF(A.COST_CODE != 1200,A.UNIT_COUNT,0)),
						@SS_TOTAL_KITCHENS = SUM(IIF(A.COST_CODE = 1200,A.UNIT_COUNT,0))
					FROM CAMA.IMP_RES_ADD_ONS A
					WHERE A.IMP_NO = @IMP_IMP_NO
						AND A.JURISDICTION = @IMP_JURISDICTION
						AND A.RECORD_TYPE = @IMP_RECORD_TYPE
						AND A.PARCEL_ID = @IMP_PARCEL_ID
						AND A.TAX_YEAR = @IMP_TAX_YEAR
						AND (A.COST_CODE = 1200 OR A.COST_CODE BETWEEN 1100 AND 1115)
				END
				ELSE
				BEGIN
					SELECT
						@IMP_IMP_NO	                                    	=	IR.IMP_NO,
						@IMP_JURISDICTION	                            	=	IR.JURISDICTION,
						@IMP_RECORD_TYPE	                                =	IR.RECORD_TYPE,
						@IMP_PARCEL_ID	                                	=	IR.PARCEL_ID,
						@IMP_TAX_YEAR	                                	=	IR.TAX_YEAR,
						@SS_QUALITY	                                    	=	IIF(@SS_QUALITY != IR.QUALITY,NULL,@SS_QUALITY),
						@SS_CONDITION	                                	=	IIF(@SS_CONDITION != IR.CONDITION,NULL,@SS_CONDITION),
						@SS_YEAR_BUILT	                                	=	IIF(@SS_YEAR_BUILT != IR.YEAR_BUILT,NULL,@SS_YEAR_BUILT),
						@SS_EFF_AGE	                            			=	IIF(@SS_EFF_AGE != IR.TAX_YEAR - IR.EFF_YEAR_BUILT,NULL,@SS_EFF_AGE),
						@SS_GLA	                                        	+=	IR.GLA,
						@SS_BASEMENT_SF	                                    +=	IR.BSMT,
						@SS_BASEMENT_FINISHED                            	+=	IR.BSMT * IR.BSMT_FINISH_PCT,
						@SS_TOTAL_BEDROOMS	                            	+=	IR.GLA_BEDROOMS
					FROM @IMP_RES_TYPE IR
					WHERE IR.ROW_ID = @I_MIN_ID

					SELECT
						@SS_TOTAL_FULL_BATHROOMS							+=	P.FULL_BATHS_3 + P.FULL_BATHS_4 + P.DELUXE_BATHS_5 + P.LUXURY_BATHS_6,
						@SS_TOTAL_HALF_BATHROOMS							+=	P.HALF_BATHS_2,
						@SS_TOTAL_THREE_QUARTER_BATHROOMS					+=	P.THREE_QTR_BATHS_3,
						@SS_TOTAL_LAUNDRY									+=	P.ROUGH_IN_FIXTURES
					FROM CAMA.IMP_RES_PLUMBING P
					WHERE P.IMP_NO = @IMP_IMP_NO
						AND P.JURISDICTION = @IMP_JURISDICTION
						AND P.RECORD_TYPE = @IMP_RECORD_TYPE
						AND P.PARCEL_ID = @IMP_PARCEL_ID
						AND P.TAX_YEAR = @IMP_TAX_YEAR

					SELECT
						@SS_TOTAL_FIREPLACES += SUM(IIF(A.COST_CODE != 1200,A.UNIT_COUNT,0)),
						@SS_TOTAL_KITCHENS += SUM(IIF(A.COST_CODE = 1200,A.UNIT_COUNT,0))
					FROM CAMA.IMP_RES_ADD_ONS A
					WHERE A.IMP_NO = @IMP_IMP_NO
						AND A.JURISDICTION = @IMP_JURISDICTION
						AND A.RECORD_TYPE = @IMP_RECORD_TYPE
						AND A.PARCEL_ID = @IMP_PARCEL_ID
						AND A.TAX_YEAR = @IMP_TAX_YEAR
						AND (A.COST_CODE = 1200 OR A.COST_CODE BETWEEN 1100 AND 1115)
				END				
				SET @I_MIN_ID += 1
			END
		END
		DELETE @IMP_RES_TYPE
		INSERT INTO @IMP_RES_TYPE
		SELECT
			IMP_NO	                                    	=	IR.IMP_NO,
			JURISDICTION	                            	=	IR.JURISDICTION,
			RECORD_TYPE			                            =	IR.RECORD_TYPE,
			PARCEL_ID	                                	=	IR.PARCEL_ID,
			TAX_YEAR	                                	=	IR.TAX_YEAR,
			QUALITY	                                    	=	IR.QUALITY,
			CONDITION	                                	=	IR.CONDITION,
			YEAR_BUILT	                                	=	IR.YEAR_BUILT,
			EFF_AGE	                            			=	IR.TAX_YEAR - IR.EFF_YEAR_BUILT,
			GLA	                                        	=	IR.GLA,
			BSMT	                                    	=	IR.BSMT,
			BSMT_FINISH_PCT	                            	=	IR.BSMT_FINISH_PCT,
			GLA_BEDROOMS	                            	=	IR.GLA_BEDROOMS
		FROM CAMA.IMP_RES IR
		INNER JOIN @SALE_PARCEL_TYPE SPT
			ON IR.JURISDICTION = SPT.SP_JURISDICTION
			AND IR.RECORD_TYPE = SPT.SP_RECORD_TYPE
			AND IR.PARCEL_ID = SPT.SP_PARCEL_ID
			AND IR.TAX_YEAR = SPT.SP_TAX_YEAR

		SET @I_MIN_ID = NULL
		SET @I_MIN_ID = (SELECT MIN(ROW_ID) FROM @IMP_RES_TYPE)
		SET @I_MAX_ID = NULL
		SET @I_MAX_ID = (SELECT MAX(ROW_ID) FROM @IMP_RES_TYPE)	

		SET @CY_TOTAL_IMP_COUNT = 0
		IF @I_MAX_ID IS NOT NULL
		BEGIN
			WHILE @I_MIN_ID <=@I_MAX_ID
			BEGIN
				SET @CY_TOTAL_IMP_COUNT += 1

				IF @CY_TOTAL_IMP_COUNT = 1
				BEGIN
					SELECT
						@IMP_IMP_NO	                                    	=	IR.IMP_NO,
						@IMP_JURISDICTION	                            	=	IR.JURISDICTION,
						@IMP_RECORD_TYPE	                                =	IR.RECORD_TYPE,
						@IMP_PARCEL_ID	                                	=	IR.PARCEL_ID,
						@IMP_TAX_YEAR	                                	=	IR.TAX_YEAR,
						@CY_QUALITY	                                    	=	IR.QUALITY,
						@CY_CONDITION	                                	=	IR.CONDITION,
						@CY_YEAR_BUILT	                                	=	IR.YEAR_BUILT,
						@CY_EFF_AGE	                            			=	IR.TAX_YEAR - IR.EFF_YEAR_BUILT,
						@CY_GLA	                                        	=	IR.GLA,
						@CY_BASEMENT_SF	                                    =	IR.BSMT,
						@CY_BASEMENT_FINISHED                            	=	IR.BSMT * IR.BSMT_FINISH_PCT,
						@CY_TOTAL_BEDROOMS	                            	=	IR.GLA_BEDROOMS
					FROM @IMP_RES_TYPE IR
					WHERE IR.ROW_ID = @I_MIN_ID

					SELECT
						@CY_TOTAL_FULL_BATHROOMS							=	P.FULL_BATHS_3 + P.FULL_BATHS_4 + P.DELUXE_BATHS_5 + P.LUXURY_BATHS_6,
						@CY_TOTAL_HALF_BATHROOMS							=	P.HALF_BATHS_2,
						@CY_TOTAL_THREE_QUARTER_BATHROOMS					=	P.THREE_QTR_BATHS_3,
						@CY_TOTAL_LAUNDRY									=	P.ROUGH_IN_FIXTURES
					FROM CAMA.IMP_RES_PLUMBING P
					WHERE P.IMP_NO = @IMP_IMP_NO
						AND P.JURISDICTION = @IMP_JURISDICTION
						AND P.RECORD_TYPE = @IMP_RECORD_TYPE
						AND P.PARCEL_ID = @IMP_PARCEL_ID
						AND P.TAX_YEAR = @IMP_TAX_YEAR

					SELECT
						@CY_TOTAL_FIREPLACES = SUM(IIF(A.COST_CODE != 1200,A.UNIT_COUNT,0)),
						@CY_TOTAL_KITCHENS = SUM(IIF(A.COST_CODE = 1200,A.UNIT_COUNT,0))
					FROM CAMA.IMP_RES_ADD_ONS A
					WHERE A.IMP_NO = @IMP_IMP_NO
						AND A.JURISDICTION = @IMP_JURISDICTION
						AND A.RECORD_TYPE = @IMP_RECORD_TYPE
						AND A.PARCEL_ID = @IMP_PARCEL_ID
						AND A.TAX_YEAR = @IMP_TAX_YEAR
						AND (A.COST_CODE = 1200 OR A.COST_CODE BETWEEN 1100 AND 1115)
				END
				ELSE
				BEGIN
					SELECT
						@IMP_IMP_NO	                                    	=	IR.IMP_NO,
						@IMP_JURISDICTION	                            	=	IR.JURISDICTION,
						@IMP_RECORD_TYPE	                                =	IR.RECORD_TYPE,
						@IMP_PARCEL_ID	                                	=	IR.PARCEL_ID,
						@IMP_TAX_YEAR	                                	=	IR.TAX_YEAR,
						@CY_QUALITY	                                    	=	IIF(@CY_QUALITY != IR.QUALITY,NULL,@CY_QUALITY),
						@CY_CONDITION	                                	=	IIF(@CY_CONDITION != IR.CONDITION,NULL,@CY_CONDITION),
						@CY_YEAR_BUILT	                                	=	IIF(@CY_YEAR_BUILT != IR.YEAR_BUILT,NULL,@CY_YEAR_BUILT),
						@CY_EFF_AGE	                            			=	IIF(@CY_EFF_AGE != IR.TAX_YEAR - IR.EFF_YEAR_BUILT,NULL,@CY_EFF_AGE),
						@CY_GLA	                                        	+=	IR.GLA,
						@CY_BASEMENT_SF	                                    +=	IR.BSMT,
						@CY_BASEMENT_FINISHED                            	+=	IR.BSMT * IR.BSMT_FINISH_PCT,
						@CY_TOTAL_BEDROOMS	                            	+=	IR.GLA_BEDROOMS
					FROM @IMP_RES_TYPE IR
					WHERE IR.ROW_ID = @I_MIN_ID

					SELECT
						@CY_TOTAL_FULL_BATHROOMS							+=	P.FULL_BATHS_3 + P.FULL_BATHS_4 + P.DELUXE_BATHS_5 + P.LUXURY_BATHS_6,
						@CY_TOTAL_HALF_BATHROOMS							+=	P.HALF_BATHS_2,
						@CY_TOTAL_THREE_QUARTER_BATHROOMS					+=	P.THREE_QTR_BATHS_3,
						@CY_TOTAL_LAUNDRY									+=	P.ROUGH_IN_FIXTURES
					FROM CAMA.IMP_RES_PLUMBING P
					WHERE P.IMP_NO = @IMP_IMP_NO
						AND P.JURISDICTION = @IMP_JURISDICTION
						AND P.RECORD_TYPE = @IMP_RECORD_TYPE
						AND P.PARCEL_ID = @IMP_PARCEL_ID
						AND P.TAX_YEAR = @IMP_TAX_YEAR

					SELECT
						@CY_TOTAL_FIREPLACES += SUM(IIF(A.COST_CODE != 1200,A.UNIT_COUNT,0)),
						@CY_TOTAL_KITCHENS += SUM(IIF(A.COST_CODE = 1200,A.UNIT_COUNT,0))
					FROM CAMA.IMP_RES_ADD_ONS A
					WHERE A.IMP_NO = @IMP_IMP_NO
						AND A.JURISDICTION = @IMP_JURISDICTION
						AND A.RECORD_TYPE = @IMP_RECORD_TYPE
						AND A.PARCEL_ID = @IMP_PARCEL_ID
						AND A.TAX_YEAR = @IMP_TAX_YEAR
						AND (A.COST_CODE = 1200 OR A.COST_CODE BETWEEN 1100 AND 1115)
				END				
				SET @I_MIN_ID += 1
			END
		END
	END

	INSERT INTO @OUTPUT
	SELECT 
		JURISDICTION								=	@JURISDICTION,
		TAX_YEAR									=	YEAR(@SALE_DATE),
		TAXABLE_STATUS								=	@SS_TAX_STATUS,
		MLS_SOURCE_NUMBER							=	@MLS_SOURCE_NUMBER,
		MLS_SOURCE_VALUE							=	@MLS_SOURCE_VALUE,
		TS_SOURCE_NUMBER							=	@TS_SOURCE_NUMBER,
		TS_SOURCE_VALUE								=	@TS_SOURCE_VALUE,
		SALE_TYPE									=	@SALE_TYPE,
		PARCEL_COUNT								=	@SALE_PARCEL_COUNT,
		PARCEL_NUMBER								=	@PARCEL_ID,
		ADDITIONAL_PARCEL_NUMBERS					=	IIF(@ADDITIONAL_PARCELS='',NULL,@ADDITIONAL_PARCELS),
		SALE_DATE									=	@SALE_DATE,
		CONTRACT_DATE								=	@CONTRACT_DATE,
		SALE_PRICE									=	@SALE_PRICE,
		CONCESSIONS									=	ISNULL(@CON_AMOUNT,0),
		ADUSTED_SALES_PRICE							=	@SALE_PRICE - ISNULL(@CON_AMOUNT,0),
		PROP_TYPE									=	@SS_PROP_TYPE ,
		PROP_TYPE_DESC								=	@PROP_TYPE_DESC,
		SPECIFIC_PROP_TYPE							=	@SS_SPECIFIC_PROP_TYPE ,
		SPEC_PROP_TYPE_DESC							=	@SPEC_PROP_TYPE_DESC,
		TAX_DIST									=	@SS_TAX_DIST ,
		NBHD_REGION									=	@REGION,
		NBHD_GROUP									=	@GROUP,
		NBHD_CODE									=	@SS_NBHD_CODE ,
		NBHD_DESCRIPION								=	@NBHD_DESC,
		SUBDIVISION									=	@SS_SUBDIVISION ,
		LAND_DISTRICT								=	@SS_LAND_DISTRICT ,
		LAND_DIST_DESC								=	@LAND_DISTRICT_DESC,
		PY_ACREAGE									=	@PY_ACREAGE,
		PY_QUALITY									=	@PY_QUALITY,
		PY_CONDITION								=	@PY_CONDITION,
		PY_BASEMENT_FINISHED						=	@PY_BASEMENT_FINISHED,
		PY_BASEMENT_SF								=	@PY_BASEMENT_SF,
		PY_TOTAL_BEDROOMS							=	@PY_TOTAL_BEDROOMS,
		PY_TOTAL_FULL_BATHROOMS						=	@PY_TOTAL_FULL_BATHROOMS,
		PY_TOTAL_THREE_QUARTER_BATHROOMS			=	@PY_TOTAL_THREE_QUARTER_BATHROOMS,
		PY_TOTAL_HALF_BATHROOMS						=	@PY_TOTAL_HALF_BATHROOMS,
		PY_TOTAL_FIREPLACES							=	@PY_TOTAL_FIREPLACES,
		PY_TOTAL_KITCHENS							=	@PY_TOTAL_KITCHENS,
		PY_TOTAL_LAUNDRY							=	@PY_TOTAL_LAUNDRY,
		PY_TOTAL_IMP_COUNT							=	@PY_TOTAL_IMP_COUNT,
		PY_GLA										=	@PY_GLA,
		PY_YEAR_BUILT								=	@PY_YEAR_BUILT,
		PY_EFF_AGE									=	@PY_EFF_AGE,
		SS_ACREAGE									=	@SS_ACREAGE ,
		SS_QUALITY									=	@SS_QUALITY,
		SS_CONDITION								=	@SS_CONDITION,
		SS_BASEMENT_FINISHED						=	@SS_BASEMENT_FINISHED,
		SS_BASEMENT_SF								=	@SS_BASEMENT_SF,
		SS_TOTAL_BEDROOMS							=	@SS_TOTAL_BEDROOMS,
		SS_TOTAL_FULL_BATHROOMS						=	@SS_TOTAL_FULL_BATHROOMS,
		SS_TOTAL_THREE_QUARTER_BATHROOMS			=	@SS_TOTAL_THREE_QUARTER_BATHROOMS,
		SS_TOTAL_HALF_BATHROOMS						=	@SS_TOTAL_HALF_BATHROOMS,
		SS_TOTAL_FIREPLACES							=	@SS_TOTAL_FIREPLACES,
		SS_TOTAL_KITCHENS							=	@SS_TOTAL_KITCHENS,
		SS_TOTAL_LAUNDRY							=	@SS_TOTAL_LAUNDRY,
		SS_TOTAL_IMP_COUNT							=	@SS_TOTAL_IMP_COUNT,
		SS_GLA										=	@SS_GLA,
		SS_YEAR_BUILT								=	@SS_YEAR_BUILT,
		SS_EFF_AGE									=	@SS_EFF_AGE,
		CY_ACREAGE									=	@CY_ACREAGE ,
		CY_QUALITY									=	@CY_QUALITY,
		CY_CONDITION								=	@CY_CONDITION,
		CY_BASEMENT_FINISHED						=	@CY_BASEMENT_FINISHED,
		CY_BASEMENT_SF								=	@CY_BASEMENT_SF,
		CY_TOTAL_BEDROOMS							=	@CY_TOTAL_BEDROOMS,
		CY_TOTAL_FULL_BATHROOMS						=	@CY_TOTAL_FULL_BATHROOMS,
		CY_TOTAL_THREE_QUARTER_BATHROOMS			=	@CY_TOTAL_THREE_QUARTER_BATHROOMS,
		CY_TOTAL_HALF_BATHROOMS						=	@CY_TOTAL_HALF_BATHROOMS,
		CY_TOTAL_FIREPLACES							=	@CY_TOTAL_FIREPLACES,
		CY_TOTAL_KITCHENS							=	@CY_TOTAL_KITCHENS,
		CY_TOTAL_LAUNDRY							=	@CY_TOTAL_LAUNDRY,
		CY_TOTAL_IMP_COUNT							=	@CY_TOTAL_IMP_COUNT,
		CY_GLA										=	@CY_GLA,
		CY_YEAR_BUILT								=	@CY_YEAR_BUILT,
		CY_EFF_AGE									=	@CY_EFF_AGE,
		TAX_YEAR									=	@TAX_YEAR,
		LAND_VALUE									=	@TOTAL_LAND_VALUE,
		IMP_VALUE									=	@TOTAL_IMP_VALUE,
		TOTAL_VALUE									=	@TOTAL_VALUE,
		SALE_VALID_MARKET							=	@SALE_VALID_MARKET,
		SALE_VALID_SRS								=	@SALE_VALID_SRS,
		STATE_CODE									=	@STATE_CODE,
		VERIFY_REASON								=	@VERIFY_REASON,
		FAA_FLAG									=	@SS_FAA,
		DETAIL_REVIEW_DATE							=	@CY_DETAIL_REVIEW_DATE,
		DETAIL_REVIEW_AREA							=	IIF(@CY_DETAIL_REVIEW_DATE BETWEEN CONVERT(DATETIME2,CAST(@TAX_YEAR - 1 AS VARCHAR(4)) + '-05-23') AND CONVERT(DATETIME2,CAST(@TAX_YEAR AS VARCHAR(4)) + '-05-22'),'YES','NO'),
		RATIO										=	IIF(ISNULL(@SALE_PRICE - ISNULL(@CON_AMOUNT,0),0) > 0,IIF(@SALE_TYPE = '3',@TOTAL_LAND_VALUE/(@SALE_PRICE - ISNULL(@CON_AMOUNT,0)),@TOTAL_VALUE/(@SALE_PRICE - ISNULL(@CON_AMOUNT,0))),0)
	SET @MIN_ID += 1
END

SET NOCOUNT ON;
SELECT
	JURISDICTION
	,PARCEL_NUMBER
	,SALE_YEAR
	,SALE_TYPE
	,SALE_DATE
	,ADUSTED_SALES_PRICE
	,NBHD_REGION
	,NBHD_CODE
	,LAND_DISTRICT
	,CY_ACREAGE
	,CY_QUALITY
	,CY_CONDITION
	,CY_BASEMENT_SF
	,CY_BASEMENT_FINISHED
	,CY_TOTAL_BEDROOMS
	,CY_TOTAL_FULL_BATHROOMS
	,CY_TOTAL_THREE_QUARTER_BATHROOMS
	,CY_TOTAL_HALF_BATHROOMS
	,CY_TOTAL_FIREPLACES
	,CY_GLA
	,CY_YEAR_BUILT
	,CY_EFF_AGE
	,TOTAL_VALUE
	,IMP_VALUE
	,LAND_VALUE
	,RATIO
FROM @OUTPUT
WHERE STATE_CODE = 'H'
	AND SALE_VALID_MARKET = 'Y'
	AND SALE_VALID_SRS = 'Y'
	AND PARCEL_NUMBER IS NOT NULL
	AND NBHD_CODE IS NOT NULL
	AND LAND_DISTRICT IS NOT NULL
	AND ADUSTED_SALES_PRICE > 100 