WITH CTE_PARCEL AS (
	SELECT PARCEL_ID, LEFT(NBHD_CODE,1) AS REGION, NBHD_CODE, LAND_DISTRICT
	FROM CAMA.PARCEL
	WHERE JURISDICTION = 7
		AND RECORD_TYPE = 'I'
		AND TAX_YEAR = 2025
		AND ACTIVE = 'Y'
		AND ACCOUNT_ID NOT LIKE 'HT-%'
),
CTE_SALE AS (
	SELECT PARCEL_ID
	FROM CAMA.SALE AS S
		INNER JOIN CAMA.SALE_PARCEL AS SP
			ON S.ID = SP.SALE_ID
	WHERE S.SALE_DATE BETWEEN '2025-01-01' AND '2025-12-31'
		AND S.STATE_CODE = 'H'
		AND S.SALE_VALID_MARKET = 'Y'
		AND S.SALE_VALID_SRS = 'Y'
		AND S.SALE_PRICE > 100
)
SELECT DISTINCT CONCAT(REGION,'|',NBHD_CODE,'|',LAND_DISTRICT) AS REGION
FROM CTE_PARCEL AS P
	INNER JOIN CTE_SALE AS S
		ON P.PARCEL_ID = S.PARCEL_ID
ORDER BY REGION